### ISSUE TITLE
Issues with redditAPI

### ISSUE THREAD

**Issue by sdk2k01** [S4DS-IEM/S4DS-Bot#18]
With the bot all-prepped up for deployment, here are some of the things that need attention, regarding `redditAPI` functionality : 
- [x] Memes take more time to load than any other functionality (i.e, `arxiv` and `kaggle`), despite an average latency of below 20ms.
- [x] Auto-posting didn't work the last time I checked, and given the complex nature of the function, there is no proper handling of errors as demanded by the same.

Since the shift has already been made from local files to environment variables for the secure storage of tokens and credentials, you are to use the same. Use `.gitignore` (or any other appropriate methods) for the same.

**Comment by sdk2k01** [comment]
It seems that the issue is likely to have arrived from using a list of 500 `memes` classified as category `"hot"` by reddit. So, for now, the first thing that needs to be done is to have an optimised approach to fetching a meme. As such, the intended purpose of this issue is to have a thread of discussions regarding the appropriate approach.

**Comment by soumyadeepkun** [comment]
Autopost was fixed, and it appears the reason behind slow loading of memes is merely due to slow api authentication of reddit.
